name: Мой первый пайплайн
on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Забираем код
        uses: actions/checkout@v4
      - name: Создаем HTML-сайт
        run: |
          echo "<h1>Привет, мир!</h1><p>Мой первый пайплайн работает!</p>" > index.html
          echo "Файл создан!"
      - name: Проверяем файл
        run: |
          if [ -f "index.html" ]; then
            echo "✅ Всё ок!"
          else
            echo "❌ Ошибка"
            exit 1
          fi
      - name: Показываем содержимое
        run: cat index.html
      - name: Сохраняем артефакт
        uses: actions/upload-artifact@v4
        with:
          name: my-website
          path: index.html
